### PR TITLE
Added SearchableGrailsDomainClassCompassClassMapperFactoryFactory

### PR DESCRIPTION
**Pull request by CounterPillow**
Perhaps a SearchableGrailsDomainClassCompassClassMapperFactoryFactoryFactory may be needed in the future for even more convenience.

### CODE REVIEW

**Comment by Profpatsch** [comment]
Since this is making its rounds on Twitter: Is this a joke?

**Comment by graemerocher** [comment]
Quite possibly

**Comment by lhz** [comment]
I think the main joke is that you can't know for sure.

**Comment by graemerocher** [comment]
Well searchable is long deprecated and based on tech long dead (compass), looking at the code now it is possibly one of the most over engineered things I have ever seen, so maybe good riddance?

**Comment by vromero** [comment]
Long name, yeah. But I'm sure you know what is inside it without opening the file. There is some value on it.

**Pull request merged**
